#!/usr/bin/env python3
"""Classify every test file as wild, transcoded, or suite.

Most of this repo is one text re-encoded into many encodings.  A minority is
bytes that were really served that way in the wild.  Telling them apart
matters: only wild bytes prove a detector works on what it will actually
meet, while transcoded files prove it can tell encodings apart at all.

The evidence is git history.  Every file is traced back through renames to
the commit that introduced its content, and that commit's message says how
the file came to exist -- "Fill 67 encoding-language coverage gaps" means
generated, "import test cases from Mark Pilgrim's chardet" means scraped
from the live web.  This covers 100% of the corpus, including the oldest
files from the 2012 imports.

Three values, because the honest answer is not binary:

``wild``
    Bytes as found: pages scraped from live sites (Mark Pilgrim's feed
    corpus), Wayback captures, files attached to real bug reports.

``transcoded``
    Generated by re-encoding some other text -- the CulturaX pipeline and
    the coverage-gap-filling runs.

``suite``
    Imported wholesale from another detector's test corpus (Ude, ENCA,
    uchardet, Chromium, Mozilla, charset-normalizer).  We know where *we*
    got them; we do not know how that project obtained them, and some
    arrived as deliberate multi-encoding sets (ENCA ships one Ukrainian
    text as four files, one per encoding).  Calling these wild would claim
    more than the evidence supports.

A second, independent signal corroborates the classification: whether a
file's decoded text also appears under another encoding.  Wild files are
98% unique, transcoded files 92% shared.  ``cross_check()`` reports it.

Usage::

    python3 scripts/provenance.py            # summary + per-encoding table
    python3 scripts/provenance.py --check    # also run the cross-check
"""

from __future__ import annotations

import argparse
import codecs
import hashlib
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

WILD = "wild"
TRANSCODED = "transcoded"
SUITE = "suite"
# Period text in an encoding Python cannot name (Kamenický, Mazovia),
# re-encoded into the supported codepage the same text would have used on a
# differently configured machine of the era.  The bytes are ours, so it is
# not wild; the text is authentic rather than modern web prose, so it is
# not ordinary transcoding either.  See scripts/transcode_historic.py.
HISTORIC = "historic"

# Substrings of the introducing commit's subject line -> provenance.
# Order matters: the first matching rule wins.  Anything unmatched falls
# through to SUITE, which is the conservative default -- it asserts only
# that we cannot show the file was either scraped or generated here.
COMMIT_RULES: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        HISTORIC,
        ("historic transcode", "Transcode historic"),
    ),
    (
        TRANSCODED,
        (
            "Add a bunch of new test files",  # 1,019 CulturaX files
            "Add new CulturaX test data",
            "fill all 114 encoding-language coverage gaps",
            "Fill 67 encoding-language coverage gaps",
            "test file generation script + initial generated files",
            "Fill 3 more gaps",
            "Better handling of historical Hebrew doc generation",
        ),
    ),
    (
        WILD,
        (
            "import test cases from Mark Pilgrim",
            "Some more fixes.",  # follow-up fixes to the Pilgrim import
            "support CP932 and test.",  # Japanese feeds, same corpus
            "Safari did not detect",
            "Fix BOM detection",
            "Turkish ISO-8859-9",
            # Files promoted from the miners: served or posted in that
            # encoding for real, then adjudicated before landing here.
            # scripts/promote_candidates.py is the only path in, and it
            # refuses pairs chardet's registry does not vouch for, so any
            # commit that promotes candidates is adding wild data.
            "wild Common Crawl",
            "wild HZ",
            "Promote ",
        ),
    ),
)


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(REPO), *args],
        capture_output=True,
        text=True,
        check=True,
    ).stdout


def data_files() -> list[str]:
    """Every current test-data file, as ``dirname/filename``."""
    found = []
    for directory in sorted(REPO.iterdir()):
        if not directory.is_dir() or directory.name.startswith((".", "scripts")):
            continue
        for path in sorted(directory.iterdir()):
            if path.is_file() and path.name != ".gitignore":
                found.append(f"{directory.name}/{path.name}")
    return found


def introducing_commits() -> dict[str, tuple[str, str]]:
    """Map each current path to the (date, subject) that introduced it.

    History is replayed oldest-first with rename detection, so a file keeps
    the origin of its content across the 2026 directory rename rather than
    appearing to have been created by it.
    """
    raw = _git(
        "log",
        "--reverse",
        "--find-renames",
        "--diff-filter=AMR",
        "--name-status",
        "--format=@@@%H|%ad|%s",
        "--date=short",
    )
    alive: dict[str, tuple[str, str]] = {}
    date = subject = ""
    for line in raw.splitlines():
        if line.startswith("@@@"):
            _, date, subject = line[3:].split("|", 2)
            continue
        if not line.strip():
            continue
        parts = line.split("\t")
        status = parts[0]
        if status.startswith("R") and len(parts) >= 3:
            alive[parts[2]] = alive.pop(parts[1], (date, subject))
        elif status.startswith("A") and len(parts) >= 2:
            alive[parts[1]] = (date, subject)
        # Modifications leave the origin alone.
    return alive


def classify_subject(subject: str) -> str:
    """Provenance implied by an introducing commit's subject line."""
    for verdict, needles in COMMIT_RULES:
        if any(needle in subject for needle in needles):
            return verdict
    return SUITE


# Filename prefixes only one tool ever writes.  Commit subjects are the
# primary signal, but relying on them alone means a transcode lands as
# `suite` whenever someone words a subject differently -- which has now
# happened twice.  These prefixes are not a guess about where a file came
# from: `promote_candidates.py` and `transcode_historic.py` are the only
# code that writes them, and each refuses pairs chardet's registry does
# not vouch for.
NAME_RULES: tuple[tuple[str, tuple[str, ...]], ...] = (
    (HISTORIC, ("historic_",)),
    (TRANSCODED, ("culturax_",)),
    # Every one of these is written by a miner and enters through
    # promote_candidates.py: cc_ from the crawl, po_ from gettext
    # catalogues, and the rest named for where they were dug out of.
    (
        WILD,
        (
            "cc_", "po_", "usenet_", "artpack_", "repo_",
            "dos_", "ebcdic_", "machfs_", "archive_",
        ),
    ),
)


def classify_name(filename: str) -> str | None:
    """Provenance implied by a filename a mining tool wrote, if any."""
    for verdict, prefixes in NAME_RULES:
        if filename.startswith(prefixes):
            return verdict
    return None


def classify_all() -> dict[str, str]:
    """Map every current test-data path to its provenance.

    The introducing commit decides, except for files whose names only one
    tool writes -- those are trusted over a subject line that may not have
    matched a rule.
    """
    origins = introducing_commits()
    result = {}
    for path in data_files():
        by_name = classify_name(path.partition("/")[2])
        if by_name is not None:
            result[path] = by_name
            continue
        date_subject = origins.get(path)
        result[path] = classify_subject(date_subject[1]) if date_subject else SUITE
    return result


# --------------------------------------------------------------------------
# Corroboration
# --------------------------------------------------------------------------


def _dir_codec(dirname: str) -> str | None:
    if dirname.startswith("None"):
        return None
    from encoding_gaps import get_codec  # noqa: PLC0415

    parts = dirname.split("-")
    for i in range(len(parts), 0, -1):
        try:
            return codecs.lookup(get_codec("-".join(parts[:i]))).name
        except LookupError:
            continue
    return None


def shared_text_paths() -> set[str]:
    """Paths whose decoded text also appears under a different encoding.

    A shared text means at least one of the copies is a re-encoding; which
    one is the original cannot be determined from the bytes alone, which is
    why this corroborates the git evidence rather than replacing it.
    """
    digests: dict[str, tuple[str, str]] = {}
    for path in data_files():
        dirname, _, _ = path.partition("/")
        codec = _dir_codec(dirname)
        if not codec:
            continue
        try:
            text = (REPO / path).read_bytes().decode(codec)
        except (UnicodeDecodeError, LookupError):
            continue
        digests[path] = (codec, hashlib.sha256(text.encode()).hexdigest())

    encodings_per_digest: dict[str, set[str]] = defaultdict(set)
    for codec, digest in digests.values():
        encodings_per_digest[digest].add(codec)
    return {
        path
        for path, (_, digest) in digests.items()
        if len(encodings_per_digest[digest]) > 1
    }


def cross_check() -> None:
    """Print git-derived provenance against the text-sharing signal."""
    verdicts = classify_all()
    shared = shared_text_paths()
    table: dict[str, list[int]] = defaultdict(lambda: [0, 0])
    for path, verdict in verdicts.items():
        table[verdict][0 if path in shared else 1] += 1
    print(f"\n{'provenance':<12} {'text shared':>12} {'text unique':>12}")
    print("-" * 38)
    for verdict, (share, unique) in sorted(table.items(), key=lambda kv: -sum(kv[1])):
        print(f"{verdict:<12} {share:>12} {unique:>12}")
    print(
        "\nWild files should be mostly text-unique and transcoded files mostly\n"
        "shared; large deviations mean a commit rule needs revisiting."
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Classify test-data provenance.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="also cross-check against the text-sharing signal",
    )
    arguments = parser.parse_args()

    sys.path.insert(0, str(Path(__file__).resolve().parent))
    verdicts = classify_all()
    counts: dict[str, int] = defaultdict(int)
    for verdict in verdicts.values():
        counts[verdict] += 1
    total = len(verdicts)
    print(f"{total} files")
    for verdict, count in sorted(counts.items(), key=lambda kv: -kv[1]):
        print(f"  {verdict:<12} {count:>5}  ({count / total:.0%})")

    per_dir: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for path, verdict in verdicts.items():
        per_dir[path.partition("/")[0]][verdict] += 1
    wild_dirs = sum(1 for stats in per_dir.values() if stats.get(WILD))
    print(f"\n{wild_dirs} of {len(per_dir)} directories contain at least one wild file")

    if arguments.check:
        cross_check()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
